removeAllWeapons player;
removeUniform player;
removeBackpack player;
removeVest player;
removeHeadgear player;
player addWeapon "ItemMap";
player addWeapon "ItemWatch";
player addWeapon "ItemCompass";
player addWeapon "ItemGPS";
player addWeapon "ItemRadio";
player addWeapon "Rangefinder";
player addWeapon "srifle_DMR_01_DMS_F";
player addWeapon "hgun_Pistol_heavy_01_snds_F";
player addHeadgear "H_Booniehat_indp";
player AddUniform "U_B_CombatUniform_mcam_tshirt";
player addVest "V_TacVest_khk";
player addbackpack "B_AssaultPack_mcamo";
player addMagazines ["10Rnd_762x51_Mag", 5];
player addMagazines ["11Rnd_45ACP_Mag", 5];
player addMagazines ["HandGrenade", 3];